theme: osuny
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  breadcrumb:
    position: after-hero
  summary:
    position: hero
  search:
    active: true
  posts:
    index:
      layout: grid
  logo:
    header: "/assets/images/logo_fr.svg"
    footer: "/assets/images/logo_fr.svg"
    
  share_links:
    enabled: true
    whatsapp: true
    facebook: true
    twitter: true
    linkedin: true
    email: true
    telegram: true
    mastodon: true
  