theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  breadcrumb:
    position: after-hero
  summary:
    position: hero
  search:
    active: true
  posts:
    index:
      layout: grid
  logo:
    header: "/assets/images/logo-design-institut.png"
    footer: "/assets/images/logo-design-institut.png"
